### ISSUE TITLE
Installation Process

### ISSUE THREAD

**Issue by temcdrm** [forgi86/dynonet#1]
Hello - would you consider packaging this for `pip install dynonet`?

dynonet is a great package that we use and would like to reference from code and publications. However, we are not Python experts and resort to constructs like the following to run dynonet:

``sys.path.append('c:/src/dynonet')``
``sys.path.append(os.path.abspath(__file__))``

Thanks

**Comment by ha7ilm** [comment]
@forgi86 thanks for sharing the code to reproduce the results.

Regarding the scripts, I think some pointers could be added to the `README` on how to run the examples.  

When running them from the root of the repo, I have:
```
→ python examples/EMPS/EMPS_test.py
Traceback (most recent call last):
  File "examples/EMPS/EMPS_test.py", line 9, in <module>
    from torchid.module.lti import MimoLinearDynamicalOperator, SisoLinearDynamicalOperator
ModuleNotFoundError: No module named 'torchid'
```

I'm trying to add all directories from the root of the repo with:

```
export PYTHONPATH="$(find $PWD/ -maxdepth 2 -type d | sed '/\/\./d' | tr '\n' ':' | sed 's/:$//')"
```

...but then running `EMPS_test.py` from its directory, apparently something is still missing:
```
→ python EMPS_test.py
Traceback (most recent call last):
  File "EMPS_test.py", line 56, in <module>
    G1.load_state_dict(torch.load(os.path.join(model_folder, "G1.pkl")))
  File "/root/miniconda3/lib/python3.8/site-packages/torch/serialization.py", line 579, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/root/miniconda3/lib/python3.8/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'models/EMPS_model/G1.pkl'
```
Update: OK, I guess I'd need to train the model...

**Comment by forgi86** [comment]
Hello all,
thanks for your interested in this code! I normally develop using the PyCharm IDE which automatically adds the 
project root to the python path. Then, I can import for instance the transfer function module with the following line 
of code:

>>> from torchid.module.lti import LinearDynamicalOperator

from any location.


* You may update the python path programmatically as @temcdrm did:
>>> sys.path.append('c:/src/dynonet')

* Otherwise, you may do it from the command line. On Linux:

$ export PYTHONPATH= ...

On windows, see for instance 

https://stackoverflow.com/questions/3701646/how-to-add-to-the-pythonpath-in-windows-so-it-finds-my-modules-packages


I have not (yet) prepared an installer for the dynonet code, but I am considering to do it in the future 
(perhaps packing a few more system identification tools in the same library). 

Cheers,
Marco

**Comment by temcdrm** [comment]
We have made a fork with setup.py/setup.cfg and readme files for the examples here: https://github.com/temcdrm/dynonet 

After another engineer tests this on a clean repository, we could make a pull request.

**Comment by forgi86** [comment]
Thanks @temcdrm! Your installer looks neat. 

Two comments:
* Perhaps I would move the util folder into torchid. IMHO it could be annoying to provide a top-level package called util, which could easily be masked by another util package from the user.

* Perhaps I would also rename torchid to something like dynonet as it is more descriptive for a package name. I was calling torchid a larger library of identification tools in pytorch (not yet released though)

Cheers,
Marco

**Comment by temcdrm** [comment]
Okay.  I wanted to minimize changes and was not sure if ```util``` was used somewhere else.  If you're sure about the renaming and flattening of the hierarchy, we can do that prior to a pull request.

**Comment by forgi86** [comment]
Hello @temcdrm, 
util provides 
* filtering.py that is only used for dynonet
*  metrics.py that in principle may be used for other purposes
Thus IMHO filtering.py should be packaged with dynonet, while metrics.py may even be left out (but it's also OK if it 
is included)

Anyway, I am looking forward to receiving your PR! I think it will make the dynonet code much easier to use.

Marco

**Comment by forgi86** [comment]
OK I'd say that the PR from @temcdrm has addressed the installation issue!
